// Generated by gencpp from file face_recognition_pkg/strangerPrompt.msg
// DO NOT EDIT!


#ifndef FACE_RECOGNITION_PKG_MESSAGE_STRANGERPROMPT_H
#define FACE_RECOGNITION_PKG_MESSAGE_STRANGERPROMPT_H

#include <ros/service_traits.h>


#include <face_recognition_pkg/strangerPromptRequest.h>
#include <face_recognition_pkg/strangerPromptResponse.h>


namespace face_recognition_pkg
{

struct strangerPrompt
{

typedef strangerPromptRequest Request;
typedef strangerPromptResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct strangerPrompt
} // namespace face_recognition_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::face_recognition_pkg::strangerPrompt > {
  static const char* value()
  {
    return "fd16295e9691f9b17f9af4d745cb5798";
  }

  static const char* value(const ::face_recognition_pkg::strangerPrompt&) { return value(); }
};

template<>
struct DataType< ::face_recognition_pkg::strangerPrompt > {
  static const char* value()
  {
    return "face_recognition_pkg/strangerPrompt";
  }

  static const char* value(const ::face_recognition_pkg::strangerPrompt&) { return value(); }
};


// service_traits::MD5Sum< ::face_recognition_pkg::strangerPromptRequest> should match
// service_traits::MD5Sum< ::face_recognition_pkg::strangerPrompt >
template<>
struct MD5Sum< ::face_recognition_pkg::strangerPromptRequest>
{
  static const char* value()
  {
    return MD5Sum< ::face_recognition_pkg::strangerPrompt >::value();
  }
  static const char* value(const ::face_recognition_pkg::strangerPromptRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::face_recognition_pkg::strangerPromptRequest> should match
// service_traits::DataType< ::face_recognition_pkg::strangerPrompt >
template<>
struct DataType< ::face_recognition_pkg::strangerPromptRequest>
{
  static const char* value()
  {
    return DataType< ::face_recognition_pkg::strangerPrompt >::value();
  }
  static const char* value(const ::face_recognition_pkg::strangerPromptRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::face_recognition_pkg::strangerPromptResponse> should match
// service_traits::MD5Sum< ::face_recognition_pkg::strangerPrompt >
template<>
struct MD5Sum< ::face_recognition_pkg::strangerPromptResponse>
{
  static const char* value()
  {
    return MD5Sum< ::face_recognition_pkg::strangerPrompt >::value();
  }
  static const char* value(const ::face_recognition_pkg::strangerPromptResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::face_recognition_pkg::strangerPromptResponse> should match
// service_traits::DataType< ::face_recognition_pkg::strangerPrompt >
template<>
struct DataType< ::face_recognition_pkg::strangerPromptResponse>
{
  static const char* value()
  {
    return DataType< ::face_recognition_pkg::strangerPrompt >::value();
  }
  static const char* value(const ::face_recognition_pkg::strangerPromptResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FACE_RECOGNITION_PKG_MESSAGE_STRANGERPROMPT_H
