// Generated by gencpp from file voice_recognition/strangerPrompt.msg
// DO NOT EDIT!


#ifndef VOICE_RECOGNITION_MESSAGE_STRANGERPROMPT_H
#define VOICE_RECOGNITION_MESSAGE_STRANGERPROMPT_H

#include <ros/service_traits.h>


#include <voice_recognition/strangerPromptRequest.h>
#include <voice_recognition/strangerPromptResponse.h>


namespace voice_recognition
{

struct strangerPrompt
{

typedef strangerPromptRequest Request;
typedef strangerPromptResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct strangerPrompt
} // namespace voice_recognition


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::voice_recognition::strangerPrompt > {
  static const char* value()
  {
    return "fd16295e9691f9b17f9af4d745cb5798";
  }

  static const char* value(const ::voice_recognition::strangerPrompt&) { return value(); }
};

template<>
struct DataType< ::voice_recognition::strangerPrompt > {
  static const char* value()
  {
    return "voice_recognition/strangerPrompt";
  }

  static const char* value(const ::voice_recognition::strangerPrompt&) { return value(); }
};


// service_traits::MD5Sum< ::voice_recognition::strangerPromptRequest> should match
// service_traits::MD5Sum< ::voice_recognition::strangerPrompt >
template<>
struct MD5Sum< ::voice_recognition::strangerPromptRequest>
{
  static const char* value()
  {
    return MD5Sum< ::voice_recognition::strangerPrompt >::value();
  }
  static const char* value(const ::voice_recognition::strangerPromptRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::voice_recognition::strangerPromptRequest> should match
// service_traits::DataType< ::voice_recognition::strangerPrompt >
template<>
struct DataType< ::voice_recognition::strangerPromptRequest>
{
  static const char* value()
  {
    return DataType< ::voice_recognition::strangerPrompt >::value();
  }
  static const char* value(const ::voice_recognition::strangerPromptRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::voice_recognition::strangerPromptResponse> should match
// service_traits::MD5Sum< ::voice_recognition::strangerPrompt >
template<>
struct MD5Sum< ::voice_recognition::strangerPromptResponse>
{
  static const char* value()
  {
    return MD5Sum< ::voice_recognition::strangerPrompt >::value();
  }
  static const char* value(const ::voice_recognition::strangerPromptResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::voice_recognition::strangerPromptResponse> should match
// service_traits::DataType< ::voice_recognition::strangerPrompt >
template<>
struct DataType< ::voice_recognition::strangerPromptResponse>
{
  static const char* value()
  {
    return DataType< ::voice_recognition::strangerPrompt >::value();
  }
  static const char* value(const ::voice_recognition::strangerPromptResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VOICE_RECOGNITION_MESSAGE_STRANGERPROMPT_H
