// Generated by gencpp from file voice_recognition/strangerPromptResponse.msg
// DO NOT EDIT!


#ifndef VOICE_RECOGNITION_MESSAGE_STRANGERPROMPTRESPONSE_H
#define VOICE_RECOGNITION_MESSAGE_STRANGERPROMPTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace voice_recognition
{
template <class ContainerAllocator>
struct strangerPromptResponse_
{
  typedef strangerPromptResponse_<ContainerAllocator> Type;

  strangerPromptResponse_()
    : respond()  {
    }
  strangerPromptResponse_(const ContainerAllocator& _alloc)
    : respond(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _respond_type;
  _respond_type respond;





  typedef boost::shared_ptr< ::voice_recognition::strangerPromptResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::voice_recognition::strangerPromptResponse_<ContainerAllocator> const> ConstPtr;

}; // struct strangerPromptResponse_

typedef ::voice_recognition::strangerPromptResponse_<std::allocator<void> > strangerPromptResponse;

typedef boost::shared_ptr< ::voice_recognition::strangerPromptResponse > strangerPromptResponsePtr;
typedef boost::shared_ptr< ::voice_recognition::strangerPromptResponse const> strangerPromptResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::voice_recognition::strangerPromptResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::voice_recognition::strangerPromptResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::voice_recognition::strangerPromptResponse_<ContainerAllocator1> & lhs, const ::voice_recognition::strangerPromptResponse_<ContainerAllocator2> & rhs)
{
  return lhs.respond == rhs.respond;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::voice_recognition::strangerPromptResponse_<ContainerAllocator1> & lhs, const ::voice_recognition::strangerPromptResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace voice_recognition

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::voice_recognition::strangerPromptResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::voice_recognition::strangerPromptResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::voice_recognition::strangerPromptResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::voice_recognition::strangerPromptResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::voice_recognition::strangerPromptResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::voice_recognition::strangerPromptResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::voice_recognition::strangerPromptResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fd16295e9691f9b17f9af4d745cb5798";
  }

  static const char* value(const ::voice_recognition::strangerPromptResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfd16295e9691f9b1ULL;
  static const uint64_t static_value2 = 0x7f9af4d745cb5798ULL;
};

template<class ContainerAllocator>
struct DataType< ::voice_recognition::strangerPromptResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "voice_recognition/strangerPromptResponse";
  }

  static const char* value(const ::voice_recognition::strangerPromptResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::voice_recognition::strangerPromptResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string respond\n"
;
  }

  static const char* value(const ::voice_recognition::strangerPromptResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::voice_recognition::strangerPromptResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.respond);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct strangerPromptResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::voice_recognition::strangerPromptResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::voice_recognition::strangerPromptResponse_<ContainerAllocator>& v)
  {
    s << indent << "respond: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.respond);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VOICE_RECOGNITION_MESSAGE_STRANGERPROMPTRESPONSE_H
